name: Conditional Check

on: [pull_request]

jobs:
  # Check paths to changed files to see if any are non-ignored.
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.filter.outputs.relevant_changes }}
    steps:
      - name: Check modified files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            relevant_changes:
              - '!(**.md|**.ipynb|myst.yml)' # Match anything that is not these
      - name: Debug paths-filter output
        run: echo "should_run=${{ steps.filter.outputs.relevant_changes }}"
      - name: Show changed files
        run: git diff --name-only ${{ github.event.pull_request.base.sha }}


  build:
    needs: check-paths
    if: needs.check-paths.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Run Check
        run: echo "Running required check."
